apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: k8s
spec:
  master:
   image: jenkins/jenkins:lts
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
  - id: k8s-automation
    credentialType: usernamePassword
    credentialID: k8s-user-pass
    targets: "jenkins/cicd/jobs/*.jenkinsfile"
    description: "k8s-automation for Kubernetes Azure"
    repositoryBranch: master
    repositoryUrl: https://github.com/mlongarai/k8s-automation.git